---
    # .github/workflows/terraform-workflow.yaml
    name: Terraform - lint
    run-name: "[${{ github.event_name }} - ${{ github.ref_name }}] Terraform executed by @${{ github.actor }}"


    on:
      push:
        branches:
          - "**"
      pull_request:
        branches:
          - main

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    env:
      terraformVersion: 1.3.6
      working_dir : "."


    jobs:
      lint:
        name: lint
        runs-on: ubuntu-20.04

        steps:
          - name: Check out code
            uses: actions/checkout@v3

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              terraform_version: ${{ env.terraformVersion }}
              terraform_wrapper: false

          - name: Verify Terraform version
            run: terraform --version

          - name: Setup Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.10'

          - name: Terraform Initialize
            run: |
              cd ${{ env.working_dir }}
              terraform init

          - name: Terraform validation
            run: |
              cd ${{ env.working_dir }}
              terraform validate

          - name: Terraform Format
            run: terraform fmt --check
